task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 8 
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /data/zhangy/ai_tod/train/images
    ann_file: /data/zhangy/ai_tod/train/annotations/train.json
    return_masks: False
    transforms:
    type: Compose
    ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  pin_memory: True
  collate_fn:
  type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
  type: CocoDetection
  img_folder: /data/zhangy/ai_tod/val/images
  ann_file: /data/zhangy/ai_tod/val/annotations/val.json
  return_masks: False
  transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  pin_memory: True
  collate_fn:
  type: BatchImageCollateFunction


