__include__: [
  '../dataset/custom_detection.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/optimizer.yml',
  '../base/skydet.yml',
]

output_dir: ./outputs/convnext_base_dfine

SKYDET:
  backbone: ConvNeXt
  encoder: SimpleEncoder

ConvNeXt:
  in_chans: 3
  depths: [3, 3, 27, 3]
  dims: [128, 256, 512, 1024]
  pretrained: dinov3_convnext_base_pretrain_lvd1689m-801f2ba9.pth
  return_idx: [1, 2, 3]

SimpleEncoder:
  in_channels: [256, 512, 1024]
  feat_strides: [8, 16, 32]

DFINETransformer:
  feat_channels: [256, 512, 1024]

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0000125
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.00025
  betas: [0.9, 0.999]
  weight_decay: 0.000125


# Increase to search for the optimal ema
epoches: 80 # 72 + 2n
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 72
  collate_fn:
    stop_epoch: 72
    ema_restart_decay: 0.9999
    base_size_repeat: 4
val_dataloader:
  total_batch_size: 4